source 'http://rubygems.org'

gem 'devise'
gem 'rails', '3.0.3'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'jquery-rails'
gem 'will_paginate', '~> 3.0.pre2'
gem 'ruby-json'
gem 'carrierwave'
gem 'rmagick'
gem 'heroku'
gem 'brazilian-rails'